[project]
name = "basicurlscanpy"
version = "0.1.0"

description = "Simple client for URLScan API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["requests>=2.32.3"]

[dependency-groups]
dev = ["mypy>=1.15.0", "ruff>=0.11.4", "types-requests>=2.32.0.20250328"]
